# Generated by Django 5.2.12 on 2026-03-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_client', models.CharField(choices=[('entreprise', 'Entreprise'), ('associe', 'Associé'), ('particulier', 'Particulier')], default='particulier', max_length=20)),
                ('raison_sociale', models.CharField(blank=True, max_length=200)),
                ('ice', models.CharField(blank=True, max_length=20)),
                ('ifu', models.CharField(blank=True, max_length=20)),
                ('rc', models.CharField(blank=True, max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Maroc', max_length=100)),
                ('contact_principal', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
